export enum Platform {
  PC = "pc",
  PLAYSTATION = "ps",
  PLAYSTATION2 = "ps2",
  PLAYSTATION3 = "ps3",
  PLAYSTATION4 = "ps4",
  PLAYSTATION5 = "ps5",
  XBOX = "xbox",
  XBOX360 = "xbox360",
  XBOXONE = "xboxone",
  XBOXONES = "xboxones",
  XBOXONEX = "xboxonex",
  XBOXS = "xboxs",
  XBOXX = "xboxx",
  WII = "wii",
  WIIU = "wiiu",
  DS = "ds",
}
